apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
spec:
  type: NodePort  # Đảm bảo rằng kiểu là NodePort
  ports:
  - port: 8180
    targetPort: 8180
    nodePort: 30008  # Cổng mà bạn muốn sử dụng để truy cập
  selector:
    app: keycloak
